---
# Shell check my scripts

name: Coverage

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: sudo apt-get install -y bash kcov

      - name: Cover
        run: kcov coverage test/test_inmembin.sh

      - name: Upload coverage (Codecov)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash <(curl -s https://codecov.io/bash) -s coverage
