---

name: "CI: X86"

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  main:
    name: "X86: ${{ matrix.shell }} on ${{ matrix.image }}"
    strategy:
      fail-fast: false
      matrix:
        shell: [bash, zsh, ash, ksh, sh]
        image: [debian, archlinux]  # Alpine cannot copy

    container:
      image: ${{ matrix.image }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: |
          # Discriminate package name
          apt=""
          case "${{ matrix.shell }}" in
            # Sh do not require install
            sh)
              :
              ;;
            # Ash is called dash
            ash)
              if [ "${{ matrix.image}}" == alpine ] \
                  || [ "${{ matrix.image}}" == archlinux ]; then
                apt=dash
              else
                apt=ash
              fi
              ;;
            ksh)
              if [ "${{ matrix.image}}" == alpine ]; then
                apt=mksh
              else
                apt=ksh
              fi
              ;;
            *)
              apt=${{ matrix.shell }}
              ;;
          esac

          # Discriminate instalation method
          case "${{ matrix.image }}" in
            alpine)
              apk update
              apk add which bash
              [ -n "$apt" ] && apk add "$apt"
              ;;
            debian)
              apt-get update
              [ -n "$apt" ] && apt-get install -y "$apt"
              ;;
            archlinux)
              pacman -Sy --noconfirm which
              [ -n "$apt" ] && pacman -Sy --noconfirm "$apt"
              [ "$apt" = dash ] && ln -s /bin/dash /bin/ash
              ;;
          esac
          exit 0

      - name: Run
        run: ${{ matrix.shell }} test/test_in_mem_bin.sh
        shell: bash
